config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :user_sgs
  resources :user_quizzes
  resources :schools
  resources :question_options
  resources :questions
  resources :quizzes
  resources :session_details
  resources :consultations
  resources :sessions
  resources :algorithms
  resources :amethods
  resources :groups
  resources :reports
  #devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations",sessions: "users/sessions"}
  devise_scope :user do  
    match '/sessions/user', to: 'users/sessions#create', via: :post
  end
  #devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :user_teachers
  resources :user_students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    #root :to => "invoices#index"
      root to: "home#index"
  end
  #root :to => redirect("/users/sign_in")
  get '/home/home', :to =>'home#home'
  get '/home/index', :to =>'home#index'
  root :to => redirect("/home/home")
  post 'sessions' => 'session_details#create'
  post 'quizzes' => 'questions#create'
  get 'quizzes' => 'questions#index'
  post 'questions' => 'question_options#create'
  get '/home/alg', :to =>'home#alg'
  get '/myuser', :to =>'home#myuser'
  get '/getmygroups/:id' =>'home#getmygroups'
  get '/getmyteachers/:id' =>'home#getmyteachers'
  put '/myuserupdatedata/:id' => 'user_students#updatemyusr'
  get '/bygroup/:id', :to =>'reports#bygroup'
  get '/gbygroupall', :to =>'reports#gbygroupall'

  
  #Ferb:
  get '/preguntas/:id', :to => 'questions#preguntas' #Trae las preguntas del quizz' especificando el id del quizz' (quizz_id)
  get '/respuestas/:id', :to => 'question_options#respuestas' #Trae las respuestas de la pregunta especificada con el id de la question' (question_id)
  get '/buscarPromedio/:id', :to => 'groups#buscarPromedio' #Trae el promedio del grupo que el profesor tenga registrado (group_id)
  post '/UserQuiz', :to => 'user_quizzes#UserQuiz'  #Agrega o modifica la tabla de user_quiz cada que revisan un examen en la app.
  get '/sessionsUser/:id', :to => 'sessions#sessionsUser'
  post '/listexam', :to => 'quizzes#listexam'
  
  get '/sessionsall', :to =>'session_details#all'
  get '/algoritmo', :to =>'exercises#algoritmo'
  get '/ex1', :to =>'exercises#ex1'
  get '/ex2', :to =>'exercises#ex2'
  get '/ex3', :to =>'exercises#ex3'
  get '/ex4', :to =>'exercises#ex4'
  get '/algoritmop', :to =>'exercises#algoritmop'
  get 'session_details/:id', :to => 'session_details#allsessions'
    #post ':controller(/:action(/:id(.:format)))'
    #get ':controller(/:action(/:id(.:format)))'
  post 'amethods/count'

end

app/models/algorithm.rb
class Algorithm < ApplicationRecord
end

app/models/amethod.rb
class Amethod < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_students, :dependent => :destroy
	has_many :user_teachers, :dependent => :destroy
end

app/models/question.rb
class Question < ApplicationRecord
	 has_many :question_options, :dependent => :destroy
	 accepts_nested_attributes_for :question_options
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	 has_many :questions, :dependent => :destroy
	 accepts_nested_attributes_for :questions
end

app/models/school.rb
class School < ApplicationRecord
	has_many :user_students, :dependent => :destroy
	has_many :user_teachers, :dependent => :destroy
end

app/models/session.rb
class Session < ApplicationRecord
	 has_many :session_details, :dependent => :destroy
	 accepts_nested_attributes_for :session_details
end

app/models/session_detail.rb
class SessionDetail < ApplicationRecord
	#belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
  before_create { generate_token(:authentication_token) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_create :create_and_associate_user, :only => :create
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def create_and_associate_user
    if self.rol == "s"
      user_s = UserStudent.new(names: self.names, lastnames: self.lastnames,name: self.name, control_number: self.control_number, user_id: self.id)
      user_s.save!
    else
      user_s = UserTeacher.new(names: self.names, lastnames: self.lastnames,name: self.name, control_number: self.control_number,user_id: self.id)
      user_s.save!
    end
  end
  
  def generate_token(column)
   begin
      self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
  end
end

app/models/user_quiz.rb
class UserQuiz < ApplicationRecord
end

app/models/user_sg.rb
class UserSg < ApplicationRecord
  belongs_to :user
  belongs_to :school
  belongs_to :group
end

app/models/user_student.rb
class UserStudent < ApplicationRecord
	has_one :school
	has_one :group
end

app/models/user_teacher.rb
class UserTeacher < ApplicationRecord
	has_one :school
	has_one :group
end

app/controllers/amethods_controller.rb
class AmethodsController < ApplicationController
  before_action :set_amethod, only: [:show, :edit, :update, :destroy]

  # GET /amethods
  # GET /amethods.json
  $cmethods = 0
  def index
    @amethods = Amethod.all
    respond_to do |format|
        format.html 
        format.json { render json: {sessions: @amethods} }
    end
    @session_details = SessionDetail.all
    @session_detail = SessionDetail.new()
  end

  def count 
    $cmethods = 1
    #redirect_to amethod_url(@amethod)
  end

  # GET /amethods/1
  # GET /amethods/1.json
  def show
    #$cmethods = 0
  end
  def news 

  end

  # GET /amethods/new
  def new
    @amethod = Amethod.new
  end

  # GET /amethods/1/edit
  def edit
  end

  # POST /amethods
  # POST /amethods.json
  def create
    @amethod = Amethod.new(amethod_params)

    respond_to do |format|
      if @amethod.save
        format.html { redirect_to @amethod, notice: 'Amethod was successfully created.' }
        format.json { render :show, status: :created, location: @amethod }
        format.js
      else
        format.html { render :new }
        format.json { render json: @amethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amethods/1
  # PATCH/PUT /amethods/1.json
  def update
    respond_to do |format|
      if @amethod.update(amethod_params)
        format.html { redirect_to @amethod, notice: 'Amethod was successfully updated.' }
        format.json { render :show, status: :ok, location: @amethod }
      else
        format.html { render :edit }
        format.json { render json: @amethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amethods/1
  # DELETE /amethods/1.json
  def destroy
    @amethod.destroy
    respond_to do |format|
      format.html { redirect_to amethods_url, notice: 'Amethod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amethod
      @amethod = Amethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amethod_params
      params.require(:amethod).permit(:name, :subject, :description, :description_subject, :skills)
    end
end

app/helpers/amethods_helper.rb
module AmethodsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/amethods/_form.html.erb
<%= form_with(model: amethod, local: true, remote: true) do |form| %>
  <% if amethod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amethod.errors.count, "error") %> prohibited this amethod from being saved:</h2>

      <ul>
      <% amethod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :amethod_name %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :amethod_subject %>
  </div>

  <div class="field tixlist">
    <%= form.label :description %>
    <%= form.trix_editor  :description, id: :amethod_description %>
  </div>

  <div class="field">
    <%= form.label :description_subject %>
    <%= form.text_field :description_subject, id: :amethod_description_subject %>
  </div>
  <select id="people" name="people"><option value="1" selected="selected">David</option></select>
  <div class="field">
    <%= form.label :skills %>
    <%= form.text_field :skills, id: :amethod_skills %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amethods/edit.html.erb
<h1>Editing Amethod</h1>

<%= render 'form', amethod: @amethod %>

<%= link_to 'Show', @amethod %> |
<%= link_to 'Back', amethods_path %>

app/views/amethods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amethods</h1>
<%= link_to 'New Amethod', new_amethod_path, id: "new_link" %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th>Description</th>
      <th>Description subject</th>
      <th>Skills</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amethods.each do |amethod| %>
      <tr>
        <td><%= amethod.name %></td>
        <td><%= amethod.subject %></td>
        <td><%= amethod.description %></td>
        <td><%= amethod.description_subject %></td>
        <td><%= amethod.skills %></td>
        <td><%= link_to 'Show', amethod %></td>
        <td><%= link_to 'Edit', edit_amethod_path(amethod) %></td>
        <td><%= link_to 'Destroy', amethod, class: 'destroyamethods', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col-md-6">
<%= render 'session_details/form', session_detail: @session_detail %>
  </div>
   <div class="col-md-6">
<%= render 'session_details/index', session_details: @session_details %>
  </div>
</div>
<br>

app/views/amethods/new.html.erb
<h1>New Amethod</h1>

<%= render 'form', amethod: @amethod %>

<%= link_to 'Back', amethods_path %>

app/views/amethods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amethod.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @amethod.subject %>
</p>

<p>
  <strong>Description:</strong>
  <div class="tixlist">
  <%= @amethod.description.html_safe %>
  </div>
</p>

<p>
  <strong>Description subject:</strong>
  <%= @amethod.description_subject %>
 
</p>

<p>
  <strong>Skills:</strong>
  <%= @amethod.skills %>
</p>
<p>
  <strong>Skills:</strong>
  <%= $cmethods %>
</p>
<%= button_to 'To 1', amethods_count_path, method: :post %>

<%= link_to 'Edit', edit_amethod_path(@amethod) %> |
<%= link_to 'Back', amethods_path %>