config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :user_sgs
  resources :user_quizzes
  resources :schools
  resources :question_options
  resources :questions
  resources :quizzes
  resources :session_details
  resources :consultations
  resources :sessions
  resources :algorithms
  resources :amethods
  resources :groups
  resources :reports
  #devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations",sessions: "users/sessions"}
  devise_scope :user do  
    match '/sessions/user', to: 'users/sessions#create', via: :post
  end
  #devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :user_teachers
  resources :user_students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    #root :to => "invoices#index"
      root to: "home#index"
  end
  #root :to => redirect("/users/sign_in")
  get '/home/home', :to =>'home#home'
  get '/home/index', :to =>'home#index'
  root :to => redirect("/home/home")
  post 'sessions' => 'session_details#create'
  post 'quizzes' => 'questions#create'
  get 'quizzes' => 'questions#index'
  post 'questions' => 'question_options#create'
  get '/home/alg', :to =>'home#alg'
  get '/myuser', :to =>'home#myuser'
  get '/getmygroups/:id' =>'home#getmygroups'
  get '/getmyteachers/:id' =>'home#getmyteachers'
  put '/myuserupdatedata/:id' => 'user_students#updatemyusr'
  get '/bygroup/:id', :to =>'reports#bygroup'
  get '/gbygroupall', :to =>'reports#gbygroupall'

  
  #Ferb:
  get '/preguntas/:id', :to => 'questions#preguntas' #Trae las preguntas del quizz' especificando el id del quizz' (quizz_id)
  get '/respuestas/:id', :to => 'question_options#respuestas' #Trae las respuestas de la pregunta especificada con el id de la question' (question_id)
  get '/buscarPromedio/:id', :to => 'groups#buscarPromedio' #Trae el promedio del grupo que el profesor tenga registrado (group_id)
  post '/UserQuiz', :to => 'user_quizzes#UserQuiz'  #Agrega o modifica la tabla de user_quiz cada que revisan un examen en la app.
  get '/sessionsUser/:id', :to => 'sessions#sessionsUser'
  post '/listexam', :to => 'quizzes#listexam'
  
  get '/sessionsall', :to =>'session_details#all'
  get '/algoritmo', :to =>'exercises#algoritmo'
  get '/ex1', :to =>'exercises#ex1'
  get '/ex2', :to =>'exercises#ex2'
  get '/ex3', :to =>'exercises#ex3'
  get '/ex4', :to =>'exercises#ex4'
  get '/algoritmop', :to =>'exercises#algoritmop'
  get 'session_details/:id', :to => 'session_details#allsessions'
    #post ':controller(/:action(/:id(.:format)))'
    #get ':controller(/:action(/:id(.:format)))'
  post 'amethods/count'

end

app/models/algorithm.rb
class Algorithm < ApplicationRecord
end

app/models/amethod.rb
class Amethod < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_students, :dependent => :destroy
	has_many :user_teachers, :dependent => :destroy
end

app/models/question.rb
class Question < ApplicationRecord
	 has_many :question_options, :dependent => :destroy
	 accepts_nested_attributes_for :question_options
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	 has_many :questions, :dependent => :destroy
	 accepts_nested_attributes_for :questions
end

app/models/school.rb
class School < ApplicationRecord
	has_many :user_students, :dependent => :destroy
	has_many :user_teachers, :dependent => :destroy
end

app/models/session.rb
class Session < ApplicationRecord
	 has_many :session_details, :dependent => :destroy
	 accepts_nested_attributes_for :session_details
end

app/models/session_detail.rb
class SessionDetail < ApplicationRecord
	#belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
  before_create { generate_token(:authentication_token) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_create :create_and_associate_user, :only => :create
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def create_and_associate_user
    if self.rol == "s"
      user_s = UserStudent.new(names: self.names, lastnames: self.lastnames,name: self.name, control_number: self.control_number, user_id: self.id)
      user_s.save!
    else
      user_s = UserTeacher.new(names: self.names, lastnames: self.lastnames,name: self.name, control_number: self.control_number,user_id: self.id)
      user_s.save!
    end
  end
  
  def generate_token(column)
   begin
      self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
  end
end

app/models/user_quiz.rb
class UserQuiz < ApplicationRecord
end

app/models/user_sg.rb
class UserSg < ApplicationRecord
  belongs_to :user
  belongs_to :school
  belongs_to :group
end

app/models/user_student.rb
class UserStudent < ApplicationRecord
	has_one :school
	has_one :group
end

app/models/user_teacher.rb
class UserTeacher < ApplicationRecord
	has_one :school
	has_one :group
end

app/controllers/user_students_controller.rb
class UserStudentsController < ApplicationController
  before_action :set_user_student, only: [:show, :edit, :update, :destroy]
  $school
  $group
  $user_id
  # GET /user_students
  # GET /user_students.json
  def index
    @user_students = UserStudent.all
  end

  # GET /user_students/1
  # GET /user_students/1.json
  def show
  end

  def updatemyusr
     @user_student = UserStudent.where("user_students.user_id = ?",params[:id])
    respond_to do |format|
      if @user_student.update(user_student_params)
        format.html { redirect_to "/myuser", notice: 'Usuario actualizado correctamente' }
        format.json { render :show, status: :ok, location: '/myuser'}
      else
        format.html { render :edit }
      end
      end
  end

  # GET /user_students/new
  def new
    @user_student = UserStudent.new
  end

  # GET /user_students/1/edit
  def edit
  end

  # POST /user_students
  # POST /user_students.json
  def create
    @user_student = UserStudent.new(user_student_params)

    respond_to do |format|
      if @user_student.save
        format.html { redirect_to @user_student, notice: 'User student was successfully created.' }
        format.json { render :show, status: :created, location: @user_student }
      else
        format.html { render :new }
        format.json { render json: @user_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_students/1
  # PATCH/PUT /user_students/1.json
  def update
    respond_to do |format|
      if @user_student.update(user_student_params)
        format.html { redirect_to "/myuser", notice: 'User student was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_student }
      else
        format.html { render :edit }
        format.json { render json: @user_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_students/1
  # DELETE /user_students/1.json
  def destroy
    @user_student.destroy
    respond_to do |format|
      format.html { redirect_to user_students_url, notice: 'User student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_student
      @user_student = UserStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_student_params
      #params.fetch(:user_student, {})
      params.require(:user_student).permit(:names,:lastnames,:name,:control_number,:carrer,:grade,:algorithm_level,:course_level,:score,:user_id,:school_id,:avatarn,:group_id,:user_teacher_id)
    end
end 

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/user_students_helper.rb
module UserStudentsHelper
end

app/views/user_students/_form.html.erb
<%= form_with(model: user_student, local: true) do |form| %>
  <% if user_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_student.errors.count, "error") %> prohibited this user_student from being saved:</h2>

      <ul>
      <% user_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <center><div id="avatarn"> </div></center>
 <div class="field" style="display: none;">
    <%= form.label :id %>
    <%= form.text_field :id, id: :us_id %>
  </div>
 <div class="field">
    <%= form.label :name,'Nombre(s)' %>
    <%= form.text_field :name, id: :us_name %>
  </div>
 <div class="field">
    <%= form.label :lastnames,'Apellido(s)' %>
    <%= form.text_field :lastnames, id: :us_lname %>
  </div>
   <div class="field">
    <%= form.label :control_number,'Número de control' %>
    <%= form.text_field :control_number, id: :us_cn_name %>
  </div>
  <div class="field">
    <%= form.label :career,'Carrera' %>
    <%= form.text_field :career, id: :us_carrer %>
  </div>
  <div class="field">
    <%= form.label :grade,'Semestre' %>
    <%= form.text_field :grade, id: :us_grade %>
  </div>  
  <br>
  <center>
  <div class="actions">
    <%= form.submit  id:'btnSave', :class => 'btn btn-warning', :value => "Guardar cambios" %>
  </div></center>
<% end %>
<script>
            
        var iconSelect;

        window.onload = function(){     
            iconSelect = new IconSelect("avatarn", 
                {'selectedIconWidth':48,
                'selectedIconHeight':48,
                'selectedBoxPadding':1,
                'iconsWidth':50,
                'iconsHeight':50,
                'boxIconSpace':1,
                'vectoralIconNumber':4,
                'horizontalIconNumber':4});

            var icons = [];
            icons.push({'iconFilePath':'/avatar_student/boy.png', 'iconValue':"/avatar_student/boy.png"});
            icons.push({'iconFilePath':'/avatar_student/girl.png', 'iconValue':"/avatar_student/girl.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-1.png', 'iconValue':"/avatar_student/boy-1.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-1.png', 'iconValue':"/avatar_student/girl-1.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-2.png', 'iconValue':"/avatar_student/boy-2.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-2.png', 'iconValue':"/avatar_student/girl-2.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-3.png', 'iconValue':"/avatar_student/boy-3.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-3.png', 'iconValue':"/avatar_student/girl-3.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-4.png', 'iconValue':"/avatar_student/boy-4.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-4.png', 'iconValue':"/avatar_student/girl-4.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-5.png', 'iconValue':"/avatar_student/boy-5.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-5.png', 'iconValue':"/avatar_student/girl-5.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-6.png', 'iconValue':"/avatar_student/boy-6.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-6.png', 'iconValue':"/avatar_student/girl-6.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-7.png', 'iconValue':"/avatar_student/boy-7.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-7.png', 'iconValue':"/avatar_student/girl-7.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-8.png', 'iconValue':"/avatar_student/boy-8.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-8.png', 'iconValue':"/avatar_student/girl-8.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-9.png', 'iconValue':"/avatar_student/boy-9.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-9.png', 'iconValue':"/avatar_student/girl-9.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-10.png', 'iconValue':"/avatar_student/boy-10.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-10.png', 'iconValue':"/avatar_student/girl-10.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-11.png', 'iconValue':"/avatar_student/boy-11.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-11.png', 'iconValue':"/avatar_student/girl-11.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-12.png', 'iconValue':"/avatar_student/boy-12.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-12.png', 'iconValue':"/avatar_student/girl-12.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-13.png', 'iconValue':"/avatar_student/boy-13.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-13.png', 'iconValue':"/avatar_student/girl-13.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-14.png', 'iconValue':"/avatar_student/boy-14.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-14.png', 'iconValue':"/avatar_student/girl-14.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-15.png', 'iconValue':"/avatar_student/boy-15.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-15.png', 'iconValue':"/avatar_student/girl-15.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-16.png', 'iconValue':"/avatar_student/boy-16.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-16.png', 'iconValue':"/avatar_student/girl-16.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-17.png', 'iconValue':"/avatar_student/boy-17.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-17.png', 'iconValue':"/avatar_student/girl-17.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-18.png', 'iconValue':"/avatar_student/boy-18.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-18.png', 'iconValue':"/avatar_student/girl-18.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-19.png', 'iconValue':"/avatar_student/boy-19.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-19.png', 'iconValue':"/avatar_student/girl-19.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-20.png', 'iconValue':"/avatar_student/boy-20.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-20.png', 'iconValue':"/avatar_student/girl-20.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-21.png', 'iconValue':"/avatar_student/boy-21.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-21.png', 'iconValue':"/avatar_student/girl-21.png"});
            icons.push({'iconFilePath':'/avatar_student/boy-22.png', 'iconValue':"/avatar_student/boy-22.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-22.png', 'iconValue':"/avatar_student/girl-22.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-23.png', 'iconValue':"/avatar_student/girl-23.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-24.png', 'iconValue':"/avatar_student/girl-24.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-25.png', 'iconValue':"/avatar_student/girl-25.png"});
            icons.push({'iconFilePath':'/avatar_student/girl-26.png', 'iconValue':"/avatar_student/girl-26.png"});

            iconSelect.refresh(icons);
            var mypicdiv1 = $('img').attr('src');
            var myid = "/user_students/" + $('input#us_id').val() + "/";
            $('div#avatarn div.selected-icon img').prop('src',mypicdiv1);
            $("#btnSave").click(function(){
              var myurl = "/" +
              document.URL.substring(document.URL.indexOf('user_student'),document.URL.indexOf('edit'));
              var mypic = $('div#avatarn').find('img').prop('src');
              console.log("my ul: " +myurl);
              console.log("my pic: " + mypic);
                  $.ajax({
                    url: myid,
                    type: 'PUT',
                    contentType: 'application/json',
                    dataType: "script",
                    data: JSON.stringify({
                      user_student: { 
                      avatarn: mypic,
                      commit: "Update Picture"
                      },_method:'put'}),
                    successs: function(r){
                      //alert(this.value + '..Guardado');
                    }, error: function(error) {
                  //alert(error);
                  }                      
                });
            });

        };
        $(document).ready(function(){
          
        });
        </script>

app/views/user_students/edit.html.erb
<h1>Editar mi usuario</h1>

<%= render 'form', user_student: @user_student %>

<%= link_to 'Mostrar', @user_student %> |
<%= link_to 'Atrás', user_students_path %>

app/views/user_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Students</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_students.each do |user_student| %>
      <tr>
        <td><%= link_to 'Show', user_student %></td>
        <td><%= link_to 'Edit', edit_user_student_path(user_student) %></td>
        <td><%= link_to 'Destroy', user_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Student', new_user_student_path %>

app/views/user_students/new.html.erb
<h1>New User Student</h1>

<%= render 'form', user_student: @user_student %>

<%= link_to 'Back', user_students_path %>

app/views/user_students/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_student_path(@user_student) %> |
<%= link_to 'Back', user_students_path %>